### ISSUE TITLE
Failed assertion: line 1147: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by sm2017** [adar2378/pin_code_fields#125]
I am using pin_code_fields@6.0.1  , When I tap field and it focused , I get this error

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.

The relevant error-causing widget was: 
  PinCodeTextField file:///C:/Projects/myapp/lib/forms/verification_form.dart:163:28
When the exception was thrown, this was the stack: 
#2      Paint.color= (dart:ui/painting.dart:1147:12)
#3      CursorPainter.paint (package:pin_code_fields/src/cursor_painter.dart:14:9)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
#5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#5978a relayoutBoundary=up5
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=40.0, 0.0<=h<=48.0)
...  size: Size(0.0, 28.0)
RenderObject: RenderCustomPaint#5978a relayoutBoundary=up5
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=40.0, 0.0<=h<=48.0)
  size: Size(0.0, 28.0)

```

**Comment by adar2378** [comment]
Setting the cursor color solves the problem
https://github.com/adar2378/pin_code_fields/issues/120#issuecomment-725425091
