### ISSUE TITLE
 LateInitializationError: Local 'command' has not been initialized.

### ISSUE THREAD

**Issue by crimsonvspurple** [adar2378/pin_code_fields#189]
Hi.

We have a barebones flutter app where we put this pin_code_fields for OTP page but every time the OTP field is selected using `autofocus` or `left mouse click`, it triggers this error in console.

Any idea what are we doing wrong or is it an issue with this library?

```
environment:
  sdk: ">=2.13.1 <3.0.0"
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
...
  pin_code_fields: ^7.2.0
```

```
Error: LateInitializationError: Local 'command' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:5460/dart_sdk.js:5041:11)
    at command$35get (http://localhost:5460/dart_sdk.js:170859:41)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:5460/dart_sdk.js:170936:41)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:5460/dart_sdk.js:157234:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:5460/dart_sdk.js:157101:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:5460/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5460/dart_sdk.js:37453:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:5460/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5460/dart_sdk.js:37453:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:5460/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at text_input.TextInput.__.[_requestAutofill] (http://localhost:5460/packages/flutter/src/services/text_input.dart.lib.js:1315:22)
    at text_input.TextInputConnection.__.requestAutofill (http://localhost:5460/packages/flutter/src/services/text_input.dart.lib.js:1060:55)
    at editable_text.EditableTextState.new.[_openInputConnection] (http://localhost:5460/packages/flutter/src/widgets/widget_span.dart.lib.js:45128:56)
    at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded] (http://localhost:5460/packages/flutter/src/widgets/widget_span.dart.lib.js:45150:37)
    at editable_text.EditableTextState.new.[_handleFocusChanged] (http://localhost:5460/packages/flutter/src/widgets/widget_span.dart.lib.js:45358:50)
    at focus_manager.FocusNode.new.notifyListeners (http://localhost:5460/packages/flutter/src/foundation/change_notifier.dart.lib.js:106:41)
    at focus_manager.FocusNode.new.[_notify] (http://localhost:5460/packages/flutter/src/widgets/widget_span.dart.lib.js:48239:12)
    at focus_manager.FocusManager.new.[_applyFocusChange] (http://localhost:5460/packages/flutter/src/widgets/widget_span.dart.lib.js:48969:26)
    at Object._microtaskLoop (http://localhost:5460/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5460/dart_sdk.js:37532:13)
    at http://localhost:5460/dart_sdk.js:33303:9
```

**Comment by ricpar11** [comment]
Same here, `web` platform related issue

**Comment by adar2378** [comment]
I think it is from Flutter's side. 

https://github.com/flutter/flutter/issues/83618
