### ISSUE TITLE
setState() called after dispose() in FocusNode Listener

### ISSUE THREAD

**Issue by KokeCacao** [adar2378/pin_code_fields#204]
```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FocusNode:
setState() called after dispose(): _PinCodeTextFieldState#309a4(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1052:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1087:6)
#2      _PinCodeTextFieldState.initState.<anonymous closure> (package:pin_code_fields/src/pin_code_fields.dart:322:7)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
#4      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1052:5)
...
The FocusNode sending notification was: FocusNode#777fd([PRIMARY FOCUS])
  context: EditableText-[LabeledGlobalKey<EditableTextState>#8aa4f]
  PRIMARY FOCUS
====================================================================================================
```

I don't understand the implementation detail of this widget, but I get this error whenever I manually focus on the text field or call `widget.focusNode.requestFocus()`

I have the widget setup like this:

```

    PinCodeTextField verificationField = PinCodeTextField(
      autoDisposeControllers: false,
      keyboardType: TextInputType.number,
      textInputAction: TextInputAction.next,
      focusNode: widget.focusNode,
      validator: pinCodeValidator,
      appContext: context,
      length: 6,
      obscureText: false,
      pinTheme: PinTheme(
        ...
      ),
      animationType: AnimationType.slide,
      enableActiveFill: false,
      onCompleted: (string) => {if (pinCodeValidator(string) == null) submit()},
      onSaved: (value) {
        _verification = value;
      },
      onChanged: (String value) {},
      beforeTextPaste: (text) => pinCodeValidator(text) == null,
    );
```

**Comment by adar2378** [comment]
It seems to me that that ` widget.focusNode` is already disposed and hence it is acting that way. Is it possible that the screen focusNode is coming from is already disposed?
