### ISSUE TITLE
Question: How to input text during widget test?

### ISSUE THREAD

**Issue by evanblasband** [adar2378/pin_code_fields#219]
I am trying to write a widget test and enter text into the pincode field and verify UI elements however I am having trouble entering text into the pincode field.  I found this similar issue for integration tests #100 but can't get a similar behavior in my widget test.  I am doing the following:
```
final pinField = find.descendant(
        of: find.byType(PinCodeTextField),
        matching: find.byType(AnimatedContainer),
      );

      await tester.tap(pinField.first);
      await tester.pump(Duration(seconds: 3));

      await tester.enterText(pinField.first, '111111');
      await tester.pump(Duration(seconds: 3));

      expect(findThisText('Please enter a valid pin'), findsOneWidget);
    });
```
but get this error when trying to enter text:
```
═╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown while running async test code:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:498:25)
#1      WidgetController.state (package:flutter_test/src/controller.dart:154:42)
#2      WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1031:42)
#3      WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1030:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1030:27)
#8      WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1057:13)
#9      WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1056:39)
#12     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#13     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1056:27)
#14     main.<anonymous closure>.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter-app/test/pinVerification_test.dart:62:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```
however the finder does return a widget:
```
6 widgets with type "AnimatedContainer" that has ancestor(s) with type "PinCodeTextField" (ignoring offstage widgets): AnimatedContainer(duration: 300ms, bg: BoxDecoration(color: Color(0xffffffff), border: , ...
```

Any help would be much appreciated.

**Comment by davidsdearaujo** [comment]
This widget test works into example project:
```dart
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    final pinField = find.descendant(
      of: find.byType(PinCodeTextField),
      matching: find.byType(AnimatedContainer),
    );
    await tester.tap(pinField.first);
    await tester.pump();

    await tester.enterText(find.byType(TextFormField).first, '3');
    await tester.pump();
    expect(find.text('3'), findsWidgets);

    await tester.pump(Duration(seconds: 2));
    expect(find.byType(FlutterLogo), findsWidgets);

    await tester.enterText(find.byType(TextFormField).first, '4');
    await tester.pump();
    expect(find.text('3'), findsWidgets);
    expect(find.text('4'), findsWidgets);
    expect(find.byType(FlutterLogo), findsWidgets);
  });
```

**Comment by Bhupesh-V** [comment]
@davidsdearaujo  Thanks for this, the code seems  
@adar2378 If it seems possible can we add this in the README itself or anywhere is a separate section of docs, it would be really helpful for users, wdyt?
