### ISSUE TITLE
 Unhandled Exception: setState() called after dispose():

### ISSUE THREAD

**Issue by dave-k** [adar2378/pin_code_fields#66]
pin_code_fields: ^3.1.2

This PinCodeTextField is used to enter an OTP (OneTimePhone) SMS code.
The first time the field is used, and _linkWithOTP() validates the code, there is no error.
When the code is not valid, and the PinCodeTextField is focused (or tapped if autoFocus: false), the error is displayed before any characters are entered.

     Unhandled Exception: setState() called after dispose():

````
Widget _smsCode() {
    return !_codeSent 
      ? SizedBox() 
      : Column(
        children: <Widget>[
          PinCodeTextField (
            autoFocus: true,
            backgroundColor: Colors.grey[50],
            length: 6,
            autoDisposeControllers: false,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            textInputType: TextInputType.number,
            controller: _smsEditingCodeController,
            pinTheme: PinTheme(
              //shape: PinCodeFieldShape.box,
              borderRadius: BorderRadius.circular(5),
              fieldHeight: 50,
              fieldWidth: 30,
              //activeFillColor: hasError ? Colors.orange : Colors.white,
            ),
            onCompleted: (String v) {
              setState(() => _smsEditingCodeController.text = '');
              _linkWithOTP(
                context: context, 
                verificationId: _verificationId, 
                smsCode: v);
            },
            onChanged: (value) {},
          ),
          Text('Enter SMS code'),
        ],
    );
  }
````

````
E/flutter (17294): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _PinCodeTextFieldState#71afa(lifecycle state: defunct, not mounted, ticker inactive)
E/flutter (17294): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (17294): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (17294): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

E/flutter (17294): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1197
E/flutter (17294): #1      State.setState 
package:flutter/…/widgets/framework.dart:1232
E/flutter (17294): #2      _PinCodeTextFieldState._setTextToInput 
package:pin_code_fields/pin_code_fields.dart:561
E/flutter (17294): #3      _PinCodeTextFieldState._assignController.<anonymous closure> 
package:pin_code_fields/pin_code_fields.dart:270
E/flutter (17294): #4      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:207
E/flutter (17294): #5      ValueNotifier.value= 
package:flutter/…/foundation/change_notifier.dart:274
E/flutter (17294): #6      TextEditingController.selection= 
package:flutter/…/widgets/editable_text.dart:194
E/flutter (17294): #7      EditableTextState._handleSelectionChanged 
package:flutter/…/widgets/editable_text.dart:1547
E/flutter (17294): #8      EditableTextState._handleFocusChanged 
package:flutter/…/widgets/editable_text.dart:1802
E/flutter (17294): #9      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:207
E/flutter (17294): #10     FocusNode._notify 
package:flutter/…/widgets/focus_manager.dart:970
E/flutter (17294): #11     FocusManager._applyFocusChange 
package:flutter/…/widgets/focus_manager.dart:1633
E/flutter (17294): #12     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter (17294): #13     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (17294): #14     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (17294): #15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (17294): #16     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (17294): #17     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (17294): #18     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (17294): #19     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (17294): #20     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (17294): #21     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
E/flutter (17294):

````

**Comment by nouveau-riche** [comment]
before using setState check this condition
if(mounted){
// write your setState code
}

**Comment by dave-k** [comment]
@nouveau-riche ````mounted```` was always true
Removing the controller solved the issue
````
/* controller: _smsEditingCodeController, */
````

**Comment by adar2378** [comment]
If you're using a TextEditingController, then make sure it doesn't get disposed when you call 

```
_linkWithOTP(
                context: context, 
                verificationId: _verificationId, 
                smsCode: v);
```

**Comment by adar2378** [comment]
I'm closing this right now. Feel free to comment for further discussion
