### ISSUE TITLE
Keyboard Repetitively Showing

### ISSUE THREAD

**Issue by Peng-Qian** [adar2378/pin_code_fields#77]
hi @adar2378 ,

Thanks for your awesome plugin, I think there is little improvement could be done.

Currently, if a user taps on the PinCodeField widget with the keyboard open, the keyboard will disappear first and then quickly show up again.

I found this may be caused by the following code.
```
  void _onFocus() {
    if (_focusNode.hasFocus) {
      _focusNode.unfocus();
      Future.delayed(const Duration(microseconds: 1),
          () => FocusScope.of(context).requestFocus(_focusNode));
    } else {
      FocusScope.of(context).requestFocus(_focusNode);
    }
  }
```
Is possible to change to this?
```
  void _onFocus() {
    if (_focusNode.hasFocus && MediaQuery.of(context).viewInsets.bottom > 0) {
      return;
    } else {
      _focusNode.requestFocus();
    }
  }
```

**Comment by adar2378** [comment]
Looks good to me. Great observation, thanks!

**Comment by adar2378** [comment]
Fixed in new update

**Comment by Peng-Qian** [comment]
Hi @adar2378 ,
I think onTap should have a default value in the constructor to avoid null input. otherwise, it will throw an exception and break function (keyboard cannot reopen).

#### Exception
```
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _PinCodeTextFieldState.build.<anonymous closure> (package:pin_code_fields/src/pin_code_fields.dart:482:31)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#9      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#15     _invoke1 (dart:ui/hooks.dart:267:10)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#d9576
```

#### Solution
```
  this.onTap = (){},
```

**Comment by adar2378** [comment]
Right right! (Y)
