### ISSUE TITLE
The method 'call' was called on null

### ISSUE THREAD

**Issue by eligijusbernotas** [adar2378/pin_code_fields#93]
I'm using the latest version (5.0.0) and if the `onTap` property is not provided then flutter throws and exception on tap 

```dart
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The method 'call' was called on null.
flutter: Receiver: null
flutter: Tried calling: call()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
flutter: #1      _PinCodeTextFieldState.build.<anonymous closure> 
package:pin_code_fields/src/pin_code_fields.dart:482
flutter: #2      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
flutter: #3      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
flutter: #4      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
flutter: #5      BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:256
flutter: #6      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:158
flutter: #7      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:224
flutter: #8      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
flutter: #9      GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
flutter: #10     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
flutter: #11     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
flutter: #15     _invoke1  (dart:ui/hooks.dart:267:10)
flutter: #16     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#7cb44
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

A simple null check should fix this or make the `onTap` property required.

**Comment by Fethi1** [comment]
i'm having the same issue

**Comment by Fethi1** [comment]
i just fixed it by removing the onSubmitted method

**Comment by adar2378** [comment]
68e40556d9eafade28ff591126436b460870d9e6 Fixed, thanks for pointing it out
